version: '2'
services:
 Redis:
  image: redis:1.0.0
  hostname: redis
  container_name: redis
  privileged: true
  volumes:
   - pgvolume:/data
  expose:
   - "22"
   - "6379"
  ports:
   - "127.0.0.1:2200:22"
   - "6379:6379"
volumes:
 pgvolume:
  external:
   name: Redis
